module;

#include <EABase/eabase.h>
#include <EASTL/array.h>
#include <EASTL/atomic.h>
#include <EASTL/chrono.h>
#include <EASTL/expected.h>
#include <EASTL/string.h>
#include <EASTL/vector.h>
#include <angelscript.h>
#include <cstdio>
#include <scriptarray.h>


import AngelEngine.NativeViewArray;
import AngelEngine.StickyContext;
import AngelEngine.Events.Interfaces;
import AngelEngine.Utils;

// Set to 1 to enable microsecond-precision timing logs for AS dispatch calls.
#define ANGEL_PROFILE_EVENTS 0

export module AngelEngine.EventChannel;

import AngelEngine.Interfaces;
import AngelEngine.Logger;
import AngelEngine.FrameAllocator;

namespace AngelEngine
{
    // ---------------------------------------------------------------------------
    // EventChannel<Args...>
    //
    // Handles the C++ side of an event channel:
    //   - Enqueue(): thread-safe batching for deferred events (OnUpdate, OnSave, OnLoad)
    //   - ProcessDeferred(): flush the queue by calling the AS dispatcher once per event
    //   - Dispatch(): synchronous immediate call (OnTick) — calls AS dispatcher directly
    //
    // Subscriber management (subscribe/unsubscribe/once) has been moved entirely
    // to the AS-side dispatcher (generated by ModuleLoader).  The C++ EventChannel
    // no longer stores individual asIScriptFunction* pointers.
    //
    // The AS dispatcher function pointer (e.g. __EngineDispatchTick__) is injected
    // via SetDispatcherFn() after module compilation.
    // ---------------------------------------------------------------------------
    export template <typename... Args>
    class EventChannel : public IEventChannel
    {
        struct ContextPrepareGuard
        {
            asIScriptContext* ctx;
            ContextPrepareGuard(asIScriptContext* c) : ctx(c) {}
            ~ContextPrepareGuard()
            {
                if (ctx)
                    ctx->Unprepare();
            }
        };

    public:
        explicit EventChannel(ChannelDescriptor descriptor) : descriptor_(eastl::move(descriptor)) {}
        ~EventChannel() override = default;

        ChannelDescriptor GetDescriptor() const override { return descriptor_; }

        // ------------------------------------------------------------------
        // Called by ScriptEngine after each (re)compile to wire the AS
        // dispatcher function.  Must be called before any Dispatch/ProcessDeferred.
        // ------------------------------------------------------------------
        void SetDispatcherFn(asIScriptEngine* engine, IContextPooling* pool, asIScriptFunction* fn) override
        {
            while (lock_.test_and_set(eastl::memory_order_acquire))
                ;
            dispatcherFn_ = fn;
            if (fn)
            {
                stickyContext_ = StickyContext(pool, engine, fn);
            }
            else
            {
                stickyContext_ = StickyContext(); // Clear existing context if fn is null
            }
            lock_.clear(eastl::memory_order_release);
        }

        void Enqueue(Args... args)
        {
            while (lock_.test_and_set(eastl::memory_order_acquire))
                ;
            if constexpr (sizeof...(Args) > 0)
            {
                EnqueueImpl(eastl::make_index_sequence<sizeof...(Args)>{}, args...);
            }
            else
            {
                count_++;
            }
            lock_.clear(eastl::memory_order_release);
        }

        // Dispatch: synchronous immediate execution — one C++→AS crossing.
        // The AS dispatcher iterates all subscribers internally (AS→AS, JIT-fast).
        eastl::expected<void, EventError> Dispatch(Args... args)
        {
            while (lock_.test_and_set(eastl::memory_order_acquire))
                ;
            if (!stickyContext_)
            {
                lock_.clear(eastl::memory_order_release);
                return {}; // No dispatcher yet (pre-compile) — silent no-op
            }

            asIScriptContext* ctx = stickyContext_.Get();

            if constexpr (sizeof...(Args) > 0)
                DispatchSetArgs(ctx, eastl::make_index_sequence<sizeof...(Args)>{}, args...);

#if ANGEL_PROFILE_EVENTS
            auto start = eastl::chrono::high_resolution_clock::now();
#endif
            int r = stickyContext_.Execute();
#if ANGEL_PROFILE_EVENTS
            auto end = eastl::chrono::high_resolution_clock::now();
            auto duration = eastl::chrono::duration_cast<eastl::chrono::microseconds>(end - start).count();
            Log::Info("[Profiler] Channel '{}' (Sync) direct execution time: {} µs", descriptor_.eventName.c_str(),
                      duration);
#endif

            lock_.clear(eastl::memory_order_release);

            if (r == asEXECUTION_EXCEPTION)
                Log::Error("Script Exception in Dispatch handler: {}", ctx->GetExceptionString());
            else if (r == asEXECUTION_ABORTED)
                Log::Error("Script Execution Aborted in Dispatch handler.");
            else if (r < 0)
                Log::Error("Script Execution Failed in Dispatch handler: {}", r);

            return {};
        }

        eastl::expected<void, EventError> ProcessDeferred() override
        {
            eastl::tuple<eastl::vector<Args>...> processingQueues;
            size_t processingCount = 0;

            // --- Critical Section: swap queues + snapshot context ---
            while (lock_.test_and_set(eastl::memory_order_acquire))
                ;

            if (!stickyContext_)
            {
                lock_.clear(eastl::memory_order_release);
                return {}; // pre-compile, no dispatcher yet
            }

            if constexpr (sizeof...(Args) > 0)
            {
                using eastl::swap;
                swap(processingQueues, queues_);
            }
            else
            {
                processingCount = count_;
                count_ = 0;
            }

            asIScriptContext* ctx = stickyContext_.Get();

            lock_.clear(eastl::memory_order_release);
            // --- End Critical Section ---

            size_t count = 0;
            if constexpr (sizeof...(Args) > 0)
                count = eastl::get<0>(processingQueues).size();
            else
                count = processingCount;

            if (count == 0)
                return {};

            if (descriptor_.isDeferred)
            {
                if constexpr (sizeof...(Args) > 0)
                {
                    eastl::tuple<NativeViewArray<Args>*...> scriptArrays{};
                    CreateArraysAndSetArgs(ctx, count, processingQueues, scriptArrays,
                                           eastl::make_index_sequence<sizeof...(Args)>{});

#if ANGEL_PROFILE_EVENTS
                    auto start = eastl::chrono::high_resolution_clock::now();
#endif
                    int r = stickyContext_.Execute();
#if ANGEL_PROFILE_EVENTS
                    auto end = eastl::chrono::high_resolution_clock::now();
                    auto duration = eastl::chrono::duration_cast<eastl::chrono::microseconds>(end - start).count();
                    Log::Info("[Profiler] Channel '{}' (Batched Arrays) deferred execution time: {} µs ({} processing)",
                              descriptor_.eventName.c_str(), duration, count);
#endif

                    if (r == asEXECUTION_EXCEPTION)
                        Log::Error("Script Exception in batched event dispatcher: {}", ctx->GetExceptionString());
                    else if (r == asEXECUTION_ABORTED)
                        Log::Error("Script Execution Aborted in batched event dispatcher.");
                    else if (r < 0)
                        Log::Error("Script Execution Failed in batched event dispatcher: {}", r);

                    ReleaseArrays(scriptArrays, eastl::make_index_sequence<sizeof...(Args)>{});
                }
                else
                {
                    ctx->SetArgDWord(0, static_cast<asDWORD>(count));
#if ANGEL_PROFILE_EVENTS
                    auto start = eastl::chrono::high_resolution_clock::now();
#endif
                    int r = stickyContext_.Execute();
#if ANGEL_PROFILE_EVENTS
                    auto end = eastl::chrono::high_resolution_clock::now();
                    auto duration = eastl::chrono::duration_cast<eastl::chrono::microseconds>(end - start).count();
                    Log::Info("[Profiler] Channel '{}' (Batched Count) deferred execution time: {} µs ({} processing)",
                              descriptor_.eventName.c_str(), duration, count);
#endif
                    if (r == asEXECUTION_EXCEPTION)
                        Log::Error("Script Exception in batched event dispatcher: {}", ctx->GetExceptionString());
                    else if (r == asEXECUTION_ABORTED)
                        Log::Error("Script Execution Aborted in batched event dispatcher.");
                    else if (r < 0)
                        Log::Error("Script Execution Failed in batched event dispatcher: {}", r);
                }
            }
            else
            {
                // One C++→AS call per event occurrence; AS dispatcher iterates subscribers.
                for (size_t i = 0; i < count; ++i)
                {
                    if constexpr (sizeof...(Args) > 0)
                        SetArgs(ctx, i, processingQueues, eastl::make_index_sequence<sizeof...(Args)>{});

#if ANGEL_PROFILE_EVENTS
                    auto start = eastl::chrono::high_resolution_clock::now();
#endif
                    int r = stickyContext_.Execute();
#if ANGEL_PROFILE_EVENTS
                    auto end = eastl::chrono::high_resolution_clock::now();
                    auto duration = eastl::chrono::duration_cast<eastl::chrono::microseconds>(end - start).count();
                    Log::Info("[Profiler] Channel '{}' (Legacy Iteration) execution time: {} µs",
                              descriptor_.eventName.c_str(), duration);
#endif

                    if (r == asEXECUTION_EXCEPTION)
                        Log::Error("Script Exception in event dispatcher: {}", ctx->GetExceptionString());
                    else if (r == asEXECUTION_ABORTED)
                        Log::Error("Script Execution Aborted in event dispatcher.");
                    else if (r < 0)
                        Log::Error("Script Execution Failed in event dispatcher: {}", r);
                }
            }
            return {};
        }

        void WarmupJIT() override
        {
            while (lock_.test_and_set(eastl::memory_order_acquire))
                ;
            if (!stickyContext_)
            {
                lock_.clear(eastl::memory_order_release);
                return;
            }
            asIScriptContext* ctx = stickyContext_.Get();
            lock_.clear(eastl::memory_order_release);

            if (descriptor_.isDeferred)
            {
                if constexpr (sizeof...(Args) > 0)
                {
                    eastl::tuple<NativeViewArray<Args>*...> scriptArrays{};
                    eastl::tuple<eastl::vector<Args>...> emptyQueues;
                    CreateArraysAndSetArgs(ctx, 0, emptyQueues, scriptArrays,
                                           eastl::make_index_sequence<sizeof...(Args)>{});
                    stickyContext_.Execute();
                    ReleaseArrays(scriptArrays, eastl::make_index_sequence<sizeof...(Args)>{});
                }
                else
                {
                    ctx->SetArgDWord(0, static_cast<asDWORD>(0));
                    stickyContext_.Execute();
                }
            }
            else
            {
                stickyContext_.Execute();
            }
        }

        void Clear() override
        {
            while (lock_.test_and_set(eastl::memory_order_acquire))
                ;
            if constexpr (sizeof...(Args) > 0)
                ClearImpl(eastl::make_index_sequence<sizeof...(Args)>{});
            count_ = 0;
            dispatcherFn_ = nullptr;
            stickyContext_ = StickyContext();
            lock_.clear(eastl::memory_order_release);
        }

    private:
        template <size_t... Is>
        void EnqueueImpl(eastl::index_sequence<Is...>, Args... args)
        {
            (eastl::get<Is>(queues_).push_back(args), ...);
        }

        template <size_t... Is>
        void DispatchSetArgs(asIScriptContext* ctx, eastl::index_sequence<Is...>, Args... args)
        {
            (AngelEngine::SetArg(ctx, static_cast<asUINT>(Is), eastl::get<Is>(eastl::forward_as_tuple(args...))), ...);
        }

        template <size_t... Is>
        void SetArgs(asIScriptContext* ctx, size_t index, const eastl::tuple<eastl::vector<Args>...>& queues,
                     eastl::index_sequence<Is...>)
        {
            (AngelEngine::SetArg(ctx, static_cast<asUINT>(Is), eastl::get<Is>(queues)[index]), ...);
        }

        template <size_t... Is>
        void ClearImpl(eastl::index_sequence<Is...>)
        {
            (eastl::get<Is>(queues_).clear(), ...);
        }

        template <size_t... Is>
        void CreateArraysAndSetArgs(asIScriptContext* ctx, size_t count,
                                    const eastl::tuple<eastl::vector<Args>...>& queues,
                                    eastl::tuple<NativeViewArray<Args>*...>& scriptArrays, eastl::index_sequence<Is...>)
        {
            (CreateArrayAndSetArg<Is>(ctx, count, eastl::get<Is>(queues), eastl::get<Is>(scriptArrays)), ...);
        }

        template <size_t I, typename T>
        void CreateArrayAndSetArg(asIScriptContext* ctx, size_t count, const eastl::vector<T>& queue,
                                  NativeViewArray<T>*& outArray)
        {
            if (descriptor_.argTypes.size() <= I)
                return;

            outArray = new NativeViewArray<T>(queue.data(), count);
            ctx->SetArgObject(static_cast<asUINT>(I), outArray);
        }

        template <size_t... Is>
        void ReleaseArrays(eastl::tuple<NativeViewArray<Args>*...>& scriptArrays, eastl::index_sequence<Is...>)
        {
            (delete eastl::get<Is>(scriptArrays), ...);
        }

        // SoA Storage: Tuple of Vectors (for deferred events with args)
        eastl::tuple<eastl::vector<Args>...> queues_;
        // AS dispatcher function — set after module compile via SetDispatcherFn()
        asIScriptFunction* dispatcherFn_ = nullptr;
        StickyContext stickyContext_{};
        eastl::atomic_flag lock_{};
        size_t count_ = 0; // Used only when sizeof...(Args) == 0
        ChannelDescriptor descriptor_;
    };
} // namespace AngelEngine
